name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "a2bcca01-f89b-43af-ac88-0286452d5483"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "1d2b79943585473da191138318dbdd8f"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "YOUR_R2_BUCKET_NAME"
preview_bucket_name = "notes-files-preview"
